import type {
  Operator,
  Product,
  Lead,
  Client,
  Policy,
  ReofferTrigger,
  Campaign,
  Partner,
  Activity,
  Quote,
} from "./types";

// ============================================================================
// OPERADORAS (top 10 PME no Brasil)
// ============================================================================
export const operators: Operator[] = [
  {
    id: "bradesco-vida",
    name: "Bradesco Vida e Previdência",
    segments: ["vida"],
    commissionRange: [0.25, 0.45],
    lives: 2800000,
    rating: 4.7,
    highlights: ["Rede nacional", "Produtos para 2+ vidas", "Reembolso ágil"],
  },
  {
    id: "icatu",
    name: "Icatu Seguros",
    segments: ["vida"],
    commissionRange: [0.28, 0.5],
    lives: 1900000,
    rating: 4.6,
    highlights: ["Especialista em vida", "Cobertura global", "Assistência funeral"],
  },
  {
    id: "prudential",
    name: "Prudential do Brasil",
    segments: ["vida"],
    commissionRange: [0.3, 0.55],
    lives: 1200000,
    rating: 4.8,
    highlights: ["Alta renda", "Consultoria patrimonial", "Expertise global"],
  },
  {
    id: "metlife",
    name: "MetLife",
    segments: ["vida", "odonto"],
    commissionRange: [0.25, 0.4],
    lives: 3400000,
    rating: 4.5,
    highlights: ["Multi-produto", "Tech friendly", "Presente em 40+ países"],
  },
  {
    id: "mag",
    name: "MAG Seguros",
    segments: ["vida"],
    commissionRange: [0.3, 0.5],
    lives: 900000,
    rating: 4.4,
    highlights: ["Tradição de 190 anos", "Mutualismo", "Planos flexíveis"],
  },
  {
    id: "amil",
    name: "Amil",
    segments: ["saude", "odonto"],
    commissionRange: [0.04, 0.08],
    lives: 3100000,
    rating: 4.2,
    highlights: ["Rede ampla São Paulo", "Coparticipação opcional", "Aceita PJs"],
  },
  {
    id: "bradesco-saude",
    name: "Bradesco Saúde",
    segments: ["saude", "odonto"],
    commissionRange: [0.04, 0.07],
    lives: 4200000,
    rating: 4.5,
    highlights: ["Nacional Plus com Einstein", "Sem coparticipação", "5+ vidas aceita PJ"],
  },
  {
    id: "sulamerica",
    name: "SulAmérica",
    segments: ["saude", "odonto", "vida", "patrimonial"],
    commissionRange: [0.04, 0.08],
    lives: 4800000,
    rating: 4.6,
    highlights: ["App mobile premium", "Rede referência", "Multi-produto"],
  },
  {
    id: "porto",
    name: "Porto Seguro",
    segments: ["patrimonial", "frota", "saude", "vida", "rc"],
    commissionRange: [0.1, 0.25],
    lives: 2200000,
    rating: 4.7,
    highlights: ["Porto Faz", "Frota inteligente", "Bundle multi-produto"],
  },
  {
    id: "allianz",
    name: "Allianz",
    segments: ["patrimonial", "frota", "rc"],
    commissionRange: [0.12, 0.28],
    lives: 1800000,
    rating: 4.5,
    highlights: ["Global leader", "RC profissional", "Cyber insurance"],
  },
];

export const operatorById = (id: string) => operators.find((o) => o.id === id);

// ============================================================================
// PRODUTOS
//
// ORDEM = ordem de prioridade comercial. SAÚDE COLETIVA é o produto principal
// da Affida PME — aparece sempre primeiro em listas, grids, footer, navegação
// e meta. Vida vira cross-sell sobre a base de saúde (não é mais o foco).
// ============================================================================
export const products: Product[] = [
  // ──────────────── 3 PRODUTOS MVP (cotação online + closer ativo) ────────
  // PDF Conselho D4.2: "Eliminar prateleira de 8 produtos no MVP: foco em
  // saúde + odonto + vida (3 produtos), com cross-sell automático após 90
  // dias de saúde ativa." Esses 3 ficam featured + mvp:true.
  {
    id: "saude-coletiva",
    code: "SAUDE_COL",
    name: "Saúde Coletiva Empresarial",
    segment: "saude",
    tagline: "Plano de saúde PME nas principais operadoras",
    description:
      "Cotação direta com Amil, Bradesco Saúde, SulAmérica, Porto Saúde, Unimed e Hapvida. Comparativo transparente por faixa etária ANS, com rede nacional, opções de coparticipação e migração da operadora atual.",
    salesMode: "self_service",
    minVidas: 2,
    avgTicket: 9800,
    featured: true,
    mvp: true,
    icon: "HeartPulse",
  },
  {
    id: "odonto-col",
    code: "ODONTO_COL",
    name: "Odontológico Empresarial",
    segment: "odonto",
    tagline: "Cross-sell natural do plano de saúde",
    description:
      "Plano odontológico com rede ampla, sem carência para urgências e ortodontia inclusa nos níveis superiores. Contratado em conjunto com saúde reduz mensalidade média.",
    salesMode: "self_service",
    minVidas: 2,
    avgTicket: 420,
    featured: true,
    mvp: true,
    icon: "Smile",
  },
  {
    id: "vida-empresarial",
    code: "VIDA_EMP",
    name: "Seguro de Vida Empresarial",
    segment: "vida",
    tagline: "Proteção para seu time, tranquilidade para o negócio",
    description:
      "Cobertura de vida em grupo para colaboradores e PJs, com capital segurado a partir de 12x o salário e assistência funeral inclusa. Cross-sell padrão sobre a carteira de saúde Affida.",
    salesMode: "self_service",
    minVidas: 2,
    avgTicket: 4200,
    featured: true,
    mvp: true,
    icon: "Shield",
  },
  // ──────────────── 5 PRODUTOS SOB CONSULTA (sem cotador no MVP) ───────────
  // Atendidos via consultor sênior por WhatsApp; sem auto-serviço até a Wave
  // 3 do PDF (D+365). Continuam listados em /cotar como linha "sob consulta"
  // para sinalizar a completude da carteira sem comprometer foco do MVP.
  {
    id: "vida-socios",
    code: "VIDA_SOCIOS",
    name: "Vida para Sócios-Chave",
    segment: "vida",
    tagline: "Blindagem patrimonial para quem lidera",
    description:
      "Seguro de vida individual para sócios e key persons com capital elevado e cobertura de invalidez por acidente e doença.",
    salesMode: "assisted",
    minVidas: 1,
    maxVidas: 10,
    avgTicket: 2800,
    icon: "Crown",
  },
  {
    id: "rc-profissional",
    code: "RC_PROF",
    name: "Responsabilidade Civil Profissional",
    segment: "rc",
    tagline: "Proteção para decisões de impacto",
    description:
      "Cobertura para erros, omissões e responsabilidade civil profissional para advogados, médicos, contadores, D&O e TI.",
    salesMode: "assisted",
    minVidas: 1,
    avgTicket: 6200,
    icon: "Scale",
  },
  {
    id: "frota-leve",
    code: "FROTA",
    name: "Seguro de Frota Empresarial",
    segment: "frota",
    tagline: "Sua frota rodando com previsibilidade",
    description:
      "Apólice única para 5+ veículos com telemetria, assistência 24h e descontos progressivos por volume.",
    salesMode: "assisted",
    minVidas: 5,
    avgTicket: 11400,
    icon: "Car",
  },
  {
    id: "patrimonial",
    code: "PATRIMONIAL",
    name: "Seguro Patrimonial PME",
    segment: "patrimonial",
    tagline: "Para o que você construiu ao longo dos anos",
    description:
      "Proteção de sede, estoque e equipamentos contra incêndio, roubo, danos elétricos e lucros cessantes.",
    salesMode: "assisted",
    minVidas: 1,
    avgTicket: 3600,
    icon: "Building2",
  },
  {
    id: "pet-corporate",
    code: "PET_CORP",
    name: "Pet Benefício Corporativo",
    segment: "pet",
    tagline: "Cuidado que encanta quem você cuida",
    description:
      "Plano pet empresarial como benefício diferencial para atração e retenção de talentos.",
    salesMode: "self_service",
    minVidas: 5,
    avgTicket: 780,
    icon: "PawPrint",
  },
];

export const productById = (id: string) => products.find((p) => p.id === id);
export const featuredProducts = products.filter((p) => p.featured);
/** PDF Conselho D4.2 — produtos do MVP (cotador online + closer ativo). */
export const mvpProducts = products.filter((p) => p.mvp);
/** PDF Conselho D4.2 — demais ramos atendidos sob consulta no MVP. */
export const consultiveProducts = products.filter((p) => !p.mvp);

// ============================================================================
// LEADS — funil ativo
// ============================================================================
export const leads: Lead[] = [
  {
    id: "lead-001",
    cnpj: "42.831.119/0001-88",
    razaoSocial: "Jurídico Martins Sociedade de Advogados",
    nomeFantasia: "Martins Advocacia",
    porte: "EPP",
    vidas: 18,
    cnae: "6911-7/01",
    ramoAtividade: "Serviços advocatícios",
    uf: "SP",
    cidade: "São Paulo",
    productOfInterest: "vida-empresarial",
    stage: "proposta",
    owner: "Ana Ribeiro",
    source: "google_ads",
    sourceDetail: "vida-empresarial-sp-broad",
    score: 82,
    estimatedPremium: 4850,
    estimatedCommission: 1940,
    createdAt: "2026-04-12T10:22:00Z",
    lastTouchAt: "2026-04-22T14:05:00Z",
    nextActionAt: "2026-04-24T10:00:00Z",
    nextAction: "Call de apresentação da proposta",
    contact: {
      nome: "Ricardo Martins",
      cargo: "Sócio diretor",
      email: "ricardo@martinsadv.com.br",
      telefone: "+55 11 98712-4431",
    },
  },
  {
    id: "lead-002",
    cnpj: "60.429.078/0001-58",
    razaoSocial: "Adiantajus Investimentos Ltda",
    nomeFantasia: "Adiantajus",
    porte: "EPP",
    vidas: 7,
    cnae: "6435-2/02",
    ramoAtividade: "Serviços financeiros",
    uf: "SP",
    cidade: "São Paulo",
    productOfInterest: "saude-coletiva",
    stage: "negociacao",
    owner: "Lucas Azevedo",
    source: "indicacao",
    sourceDetail: "Parceiro Contador AuditCont",
    score: 91,
    estimatedPremium: 9101,
    estimatedCommission: 546,
    createdAt: "2026-03-18T09:00:00Z",
    lastTouchAt: "2026-04-21T16:30:00Z",
    nextActionAt: "2026-04-25T09:30:00Z",
    nextAction: "Fechamento — decisão entre Opção 1 e 2",
    contact: {
      nome: "Beatriz Gomes",
      cargo: "Controller",
      email: "beatriz@adiantajus.com.br",
      telefone: "+55 11 99812-0099",
    },
  },
  {
    id: "lead-003",
    cnpj: "18.554.290/0001-12",
    razaoSocial: "TecnoVerde Sistemas Ltda",
    nomeFantasia: "TecnoVerde",
    porte: "ME",
    vidas: 12,
    cnae: "6202-3/00",
    ramoAtividade: "Desenvolvimento de software",
    uf: "SP",
    cidade: "Campinas",
    productOfInterest: "vida-empresarial",
    stage: "qualificado",
    owner: "Ana Ribeiro",
    source: "meta_ads",
    sourceDetail: "vida-tech-sp-lookalike",
    score: 74,
    estimatedPremium: 2980,
    estimatedCommission: 1192,
    createdAt: "2026-04-18T13:15:00Z",
    lastTouchAt: "2026-04-22T11:20:00Z",
    nextActionAt: "2026-04-24T14:00:00Z",
    nextAction: "Envio de cotação self-service",
    contact: {
      nome: "Felipe Okabe",
      cargo: "CTO & Co-founder",
      email: "felipe@tecnoverde.dev",
      telefone: "+55 19 99887-1020",
    },
  },
  {
    id: "lead-004",
    cnpj: "24.118.775/0001-39",
    razaoSocial: "Clínica Dom Pedro Ltda",
    nomeFantasia: "Clínica Dom Pedro",
    porte: "EPP",
    vidas: 22,
    cnae: "8630-5/03",
    ramoAtividade: "Clínica médica",
    uf: "RJ",
    cidade: "Rio de Janeiro",
    productOfInterest: "rc-profissional",
    stage: "proposta",
    owner: "Juliana Paes",
    source: "organico",
    sourceDetail: "Blog: RC médico — guia 2026",
    score: 79,
    estimatedPremium: 12400,
    estimatedCommission: 2480,
    createdAt: "2026-04-10T08:42:00Z",
    lastTouchAt: "2026-04-23T10:15:00Z",
    nextActionAt: "2026-04-26T11:00:00Z",
    nextAction: "Follow-up da proposta enviada",
    contact: {
      nome: "Dra. Maria Santos",
      cargo: "Diretora Clínica",
      email: "maria@domped.com.br",
      telefone: "+55 21 98230-7766",
    },
  },
  {
    id: "lead-005",
    cnpj: "89.340.228/0001-04",
    razaoSocial: "Logística Horizonte Ltda",
    nomeFantasia: "Horizonte Log",
    porte: "Media",
    vidas: 45,
    cnae: "4930-2/02",
    ramoAtividade: "Transporte rodoviário de carga",
    uf: "SP",
    cidade: "Guarulhos",
    productOfInterest: "frota-leve",
    stage: "negociacao",
    owner: "Juliana Paes",
    source: "linkedin" as unknown as Lead["source"],
    sourceDetail: "Outbound closer",
    score: 87,
    estimatedPremium: 28900,
    estimatedCommission: 5780,
    createdAt: "2026-03-28T16:00:00Z",
    lastTouchAt: "2026-04-22T09:50:00Z",
    nextActionAt: "2026-04-24T16:00:00Z",
    nextAction: "Reunião presencial — revisão de frota",
    contact: {
      nome: "Paulo Hernandes",
      cargo: "Diretor de Operações",
      email: "paulo@horizontelog.com.br",
      telefone: "+55 11 98120-4488",
    },
  },
  {
    id: "lead-006",
    cnpj: "11.290.884/0001-77",
    razaoSocial: "Café do Parque Alimentos Ltda",
    nomeFantasia: "Café do Parque",
    porte: "ME",
    vidas: 9,
    cnae: "5611-2/01",
    ramoAtividade: "Restaurantes",
    uf: "MG",
    cidade: "Belo Horizonte",
    productOfInterest: "odonto-col",
    stage: "fechado",
    owner: "Ana Ribeiro",
    source: "site",
    sourceDetail: "Self-service completo",
    score: 95,
    estimatedPremium: 440,
    estimatedCommission: 176,
    createdAt: "2026-04-15T11:00:00Z",
    lastTouchAt: "2026-04-20T15:10:00Z",
    contact: {
      nome: "Juliana Prado",
      cargo: "Sócia",
      email: "juliana@cafedoparque.com.br",
      telefone: "+55 31 98877-2211",
    },
  },
  {
    id: "lead-007",
    cnpj: "55.338.112/0001-20",
    razaoSocial: "ConstrucFácil Empreendimentos Ltda",
    nomeFantasia: "ConstrucFácil",
    porte: "EPP",
    vidas: 28,
    cnae: "4120-4/00",
    ramoAtividade: "Construção civil",
    uf: "PR",
    cidade: "Curitiba",
    productOfInterest: "vida-empresarial",
    stage: "novo",
    owner: "Lucas Azevedo",
    source: "whatsapp",
    sourceDetail: "Bot WhatsApp — link biografia Instagram",
    score: 58,
    estimatedPremium: 6200,
    estimatedCommission: 2480,
    createdAt: "2026-04-23T08:15:00Z",
    lastTouchAt: "2026-04-23T08:15:00Z",
    nextActionAt: "2026-04-23T17:00:00Z",
    nextAction: "Qualificação inicial SDR",
    contact: {
      nome: "Rogério Lima",
      cargo: "Gerente de RH",
      email: "rh@construcfacil.com",
      telefone: "+55 41 99112-7788",
    },
  },
  {
    id: "lead-008",
    cnpj: "74.128.559/0001-61",
    razaoSocial: "Boutique Aurora Comércio Ltda",
    nomeFantasia: "Boutique Aurora",
    porte: "ME",
    vidas: 6,
    cnae: "4781-4/00",
    ramoAtividade: "Comércio varejista de vestuário",
    uf: "RS",
    cidade: "Porto Alegre",
    productOfInterest: "patrimonial",
    stage: "qualificado",
    owner: "Juliana Paes",
    source: "parceiro",
    sourceDetail: "Sindilojas-POA",
    score: 68,
    estimatedPremium: 4100,
    estimatedCommission: 820,
    createdAt: "2026-04-19T14:30:00Z",
    lastTouchAt: "2026-04-22T10:00:00Z",
    nextActionAt: "2026-04-25T10:00:00Z",
    nextAction: "Envio de cotação inicial",
    contact: {
      nome: "Silvia Barcellos",
      cargo: "Proprietária",
      email: "silvia@boutiqueaurora.com.br",
      telefone: "+55 51 99887-6655",
    },
  },
  {
    id: "lead-009",
    cnpj: "90.442.281/0001-15",
    razaoSocial: "MedAssist Saúde Corporativa S/A",
    nomeFantasia: "MedAssist",
    porte: "Media",
    vidas: 86,
    cnae: "8630-5/02",
    ramoAtividade: "Clínica especializada",
    uf: "SP",
    cidade: "São Paulo",
    productOfInterest: "saude-coletiva",
    stage: "proposta",
    owner: "Lucas Azevedo",
    source: "google_ads",
    sourceDetail: "saude-coletiva-sp-exact",
    score: 88,
    estimatedPremium: 98200,
    estimatedCommission: 5892,
    createdAt: "2026-04-05T09:00:00Z",
    lastTouchAt: "2026-04-23T11:45:00Z",
    nextActionAt: "2026-04-24T15:30:00Z",
    nextAction: "Apresentação da proposta — 4 operadoras",
    contact: {
      nome: "Roberta Lins",
      cargo: "Head of People",
      email: "roberta.lins@medassist.com.br",
      telefone: "+55 11 97744-1122",
    },
  },
  {
    id: "lead-010",
    cnpj: "33.715.492/0001-50",
    razaoSocial: "Ateliê Verde Arquitetura Ltda",
    nomeFantasia: "Ateliê Verde",
    porte: "ME",
    vidas: 5,
    cnae: "7111-1/00",
    ramoAtividade: "Arquitetura",
    uf: "SP",
    cidade: "São Paulo",
    productOfInterest: "vida-socios",
    stage: "novo",
    owner: "Ana Ribeiro",
    source: "indicacao",
    sourceDetail: "Cliente atual Martins Advocacia",
    score: 72,
    estimatedPremium: 3200,
    estimatedCommission: 1440,
    createdAt: "2026-04-22T17:00:00Z",
    lastTouchAt: "2026-04-22T17:00:00Z",
    nextActionAt: "2026-04-24T09:00:00Z",
    nextAction: "Primeiro contato + call discovery",
    contact: {
      nome: "Camila Rossetti",
      cargo: "Sócia fundadora",
      email: "camila@ateliverd.com.br",
      telefone: "+55 11 98008-4422",
    },
  },
  {
    id: "lead-011",
    cnpj: "65.890.331/0001-09",
    razaoSocial: "E-commerce ModaTotal Ltda",
    nomeFantasia: "ModaTotal",
    porte: "Media",
    vidas: 62,
    cnae: "4781-4/00",
    ramoAtividade: "E-commerce de moda",
    uf: "SP",
    cidade: "São Paulo",
    productOfInterest: "vida-empresarial",
    stage: "fechado",
    owner: "Lucas Azevedo",
    source: "meta_ads",
    sourceDetail: "vida-empresarial-lookalike-converted",
    score: 93,
    estimatedPremium: 18900,
    estimatedCommission: 7560,
    createdAt: "2026-03-12T11:00:00Z",
    lastTouchAt: "2026-04-10T14:30:00Z",
    contact: {
      nome: "André Takahashi",
      cargo: "CEO",
      email: "andre@modatotal.com.br",
      telefone: "+55 11 97788-3322",
    },
  },
  {
    id: "lead-012",
    cnpj: "21.887.004/0001-44",
    razaoSocial: "Doceria Brigadeiria Lele Ltda",
    nomeFantasia: "Brigadeiria Lele",
    porte: "ME",
    vidas: 4,
    cnae: "4721-1/02",
    ramoAtividade: "Comércio de doces",
    uf: "SP",
    cidade: "São Paulo",
    productOfInterest: "odonto-col",
    stage: "perdido",
    owner: "Ana Ribeiro",
    source: "whatsapp",
    sourceDetail: "Bot WhatsApp — cotação automática",
    score: 41,
    estimatedPremium: 180,
    estimatedCommission: 72,
    createdAt: "2026-04-08T10:00:00Z",
    lastTouchAt: "2026-04-15T11:20:00Z",
    contact: {
      nome: "Lele Rodrigues",
      cargo: "Sócia",
      email: "lele@brigadeirialele.com.br",
      telefone: "+55 11 97600-8877",
    },
  },
];

// ============================================================================
// CLIENTES — carteira ativa
// ============================================================================
export const clients: Client[] = [
  {
    id: "cli-001",
    cnpj: "60.429.078/0001-58",
    razaoSocial: "Adiantajus Investimentos Ltda",
    nomeFantasia: "Adiantajus",
    porte: "EPP",
    cnae: "6435-2/02",
    ramoAtividade: "Serviços financeiros",
    uf: "SP",
    cidade: "São Paulo",
    vidas: 7,
    sinceAt: "2025-04-01",
    owner: "Lucas Azevedo",
    segments: ["saude", "vida"],
    monthlyRevenue: 546,
    status: "em_renovacao",
    nps: 9,
  },
  {
    id: "cli-002",
    cnpj: "65.890.331/0001-09",
    razaoSocial: "E-commerce ModaTotal Ltda",
    nomeFantasia: "ModaTotal",
    porte: "Media",
    cnae: "4781-4/00",
    ramoAtividade: "E-commerce de moda",
    uf: "SP",
    cidade: "São Paulo",
    vidas: 62,
    sinceAt: "2025-10-01",
    owner: "Lucas Azevedo",
    segments: ["vida", "saude", "odonto"],
    monthlyRevenue: 7560,
    status: "ativo",
    nps: 10,
  },
  {
    id: "cli-003",
    cnpj: "11.290.884/0001-77",
    razaoSocial: "Café do Parque Alimentos Ltda",
    nomeFantasia: "Café do Parque",
    porte: "ME",
    cnae: "5611-2/01",
    ramoAtividade: "Restaurantes",
    uf: "MG",
    cidade: "Belo Horizonte",
    vidas: 9,
    sinceAt: "2026-04-20",
    owner: "Ana Ribeiro",
    segments: ["odonto"],
    monthlyRevenue: 176,
    status: "ativo",
    nps: 8,
  },
  {
    id: "cli-004",
    cnpj: "42.831.119/0001-88",
    razaoSocial: "Jurídico Martins Sociedade de Advogados",
    nomeFantasia: "Martins Advocacia",
    porte: "EPP",
    cnae: "6911-7/01",
    ramoAtividade: "Serviços advocatícios",
    uf: "SP",
    cidade: "São Paulo",
    vidas: 18,
    sinceAt: "2024-06-10",
    owner: "Ana Ribeiro",
    segments: ["vida", "rc-profissional"],
    monthlyRevenue: 3280,
    status: "ativo",
    nps: 9,
  },
  {
    id: "cli-005",
    cnpj: "38.009.115/0001-93",
    razaoSocial: "Padaria Pão Quente Ltda",
    nomeFantasia: "Pão Quente",
    porte: "ME",
    cnae: "1091-1/02",
    ramoAtividade: "Padaria e confeitaria",
    uf: "SP",
    cidade: "São Bernardo do Campo",
    vidas: 14,
    sinceAt: "2024-11-01",
    owner: "Juliana Paes",
    segments: ["vida"],
    monthlyRevenue: 520,
    status: "churn_risk",
    nps: 6,
  },
  {
    id: "cli-006",
    cnpj: "47.338.102/0001-16",
    razaoSocial: "Stella Cosmética Ltda",
    nomeFantasia: "Stella Cosméticos",
    porte: "EPP",
    cnae: "4646-0/01",
    ramoAtividade: "Distribuição de cosméticos",
    uf: "SP",
    cidade: "Barueri",
    vidas: 31,
    sinceAt: "2023-09-15",
    owner: "Lucas Azevedo",
    segments: ["saude", "vida", "odonto"],
    monthlyRevenue: 4100,
    status: "ativo",
    nps: 10,
  },
  {
    id: "cli-007",
    cnpj: "72.441.909/0001-32",
    razaoSocial: "Marmoraria Bellaverde Ltda",
    nomeFantasia: "Bellaverde Mármores",
    porte: "ME",
    cnae: "2391-5/03",
    ramoAtividade: "Serviços de mármores",
    uf: "SP",
    cidade: "Itaquaquecetuba",
    vidas: 11,
    sinceAt: "2025-01-12",
    owner: "Juliana Paes",
    segments: ["vida", "patrimonial"],
    monthlyRevenue: 1280,
    status: "inadimplente",
    nps: 5,
  },
  {
    id: "cli-008",
    cnpj: "51.228.447/0001-20",
    razaoSocial: "Farma Saúde Distribuidora Ltda",
    nomeFantasia: "Farma Saúde",
    porte: "Media",
    cnae: "4644-3/01",
    ramoAtividade: "Distribuição farmacêutica",
    uf: "PR",
    cidade: "Curitiba",
    vidas: 54,
    sinceAt: "2024-03-01",
    owner: "Lucas Azevedo",
    segments: ["vida", "saude"],
    monthlyRevenue: 6200,
    status: "em_renovacao",
    nps: 9,
  },
];

export const clientById = (id: string) => clients.find((c) => c.id === id);

// ============================================================================
// APÓLICES
// ============================================================================
export const policies: Policy[] = [
  {
    id: "pol-001",
    clientId: "cli-001",
    product: "saude-coletiva",
    operatorId: "amil",
    plano: "S380 / S750 / S2500 — Opção 1",
    vigenciaInicio: "2025-04-01",
    vigenciaFim: "2026-03-31",
    premioMensal: 7586,
    comissaoPercent: 0.06,
    vidas: 7,
    status: "em_renovacao",
    coparticipacao: "parcial",
    acomodacao: "apartamento",
    abrangencia: "nacional",
  },
  {
    id: "pol-002",
    clientId: "cli-001",
    product: "vida-empresarial",
    operatorId: "icatu",
    plano: "Vida Empresa Plus",
    vigenciaInicio: "2025-04-01",
    vigenciaFim: "2026-03-31",
    premioMensal: 820,
    comissaoPercent: 0.42,
    vidas: 7,
    status: "em_renovacao",
    coparticipacao: "sem",
  },
  {
    id: "pol-003",
    clientId: "cli-002",
    product: "vida-empresarial",
    operatorId: "bradesco-vida",
    plano: "Bradesco Vida Grupo Premium",
    vigenciaInicio: "2025-10-01",
    vigenciaFim: "2026-09-30",
    premioMensal: 18900,
    comissaoPercent: 0.4,
    vidas: 62,
    status: "ativa",
    coparticipacao: "sem",
  },
  {
    id: "pol-004",
    clientId: "cli-002",
    product: "saude-coletiva",
    operatorId: "sulamerica",
    plano: "SulAmérica Exato 400 Nacional",
    vigenciaInicio: "2025-10-01",
    vigenciaFim: "2026-09-30",
    premioMensal: 41800,
    comissaoPercent: 0.05,
    vidas: 62,
    status: "ativa",
    coparticipacao: "parcial",
    acomodacao: "enfermaria",
    abrangencia: "nacional",
  },
  {
    id: "pol-005",
    clientId: "cli-003",
    product: "odonto-col",
    operatorId: "metlife",
    plano: "MetLife Odonto Nacional",
    vigenciaInicio: "2026-04-20",
    vigenciaFim: "2027-04-19",
    premioMensal: 440,
    comissaoPercent: 0.4,
    vidas: 9,
    status: "ativa",
    coparticipacao: "sem",
  },
  {
    id: "pol-006",
    clientId: "cli-004",
    product: "vida-empresarial",
    operatorId: "prudential",
    plano: "Prudential Key Person Plus",
    vigenciaInicio: "2024-06-10",
    vigenciaFim: "2026-06-09",
    premioMensal: 2680,
    comissaoPercent: 0.45,
    vidas: 18,
    status: "ativa",
    coparticipacao: "sem",
  },
  {
    id: "pol-007",
    clientId: "cli-004",
    product: "rc-profissional",
    operatorId: "allianz",
    plano: "Allianz E&O Advocacia",
    vigenciaInicio: "2024-06-10",
    vigenciaFim: "2026-06-09",
    premioMensal: 4200,
    comissaoPercent: 0.22,
    vidas: 18,
    status: "ativa",
    coparticipacao: "sem",
  },
  {
    id: "pol-008",
    clientId: "cli-005",
    product: "vida-empresarial",
    operatorId: "mag",
    plano: "MAG Empresa Start",
    vigenciaInicio: "2024-11-01",
    vigenciaFim: "2026-10-31",
    premioMensal: 1260,
    comissaoPercent: 0.38,
    vidas: 14,
    status: "ativa",
    coparticipacao: "sem",
  },
  {
    id: "pol-009",
    clientId: "cli-006",
    product: "saude-coletiva",
    operatorId: "bradesco-saude",
    plano: "Bradesco Nacional III",
    vigenciaInicio: "2023-09-15",
    vigenciaFim: "2026-09-14",
    premioMensal: 34800,
    comissaoPercent: 0.05,
    vidas: 31,
    status: "ativa",
    coparticipacao: "sem",
    acomodacao: "apartamento",
    abrangencia: "nacional",
  },
  {
    id: "pol-010",
    clientId: "cli-006",
    product: "vida-empresarial",
    operatorId: "prudential",
    plano: "Prudential Vida Grupo",
    vigenciaInicio: "2023-09-15",
    vigenciaFim: "2026-09-14",
    premioMensal: 3420,
    comissaoPercent: 0.42,
    vidas: 31,
    status: "ativa",
    coparticipacao: "sem",
  },
  {
    id: "pol-011",
    clientId: "cli-007",
    product: "vida-empresarial",
    operatorId: "mag",
    plano: "MAG Empresa Start",
    vigenciaInicio: "2025-01-12",
    vigenciaFim: "2027-01-11",
    premioMensal: 980,
    comissaoPercent: 0.38,
    vidas: 11,
    status: "suspensa",
    coparticipacao: "sem",
  },
  {
    id: "pol-012",
    clientId: "cli-008",
    product: "saude-coletiva",
    operatorId: "unimed-curitiba" as string,
    plano: "Unimed Nacional PME",
    vigenciaInicio: "2024-03-01",
    vigenciaFim: "2026-02-28",
    premioMensal: 72800,
    comissaoPercent: 0.04,
    vidas: 54,
    status: "em_renovacao",
    coparticipacao: "sem",
    acomodacao: "apartamento",
    abrangencia: "nacional",
  },
];

// ============================================================================
// GATILHOS DE RE-OFERTA — coração da tese
// ============================================================================
export const reofferTriggers: ReofferTrigger[] = [
  {
    id: "trig-001",
    policyId: "pol-001",
    clientId: "cli-001",
    type: "aniversario_60d",
    severity: "high",
    detectedAt: "2026-04-18T08:00:00Z",
    title: "Renovação em 60 dias — Adiantajus Saúde Amil",
    rationale:
      "Apólice vence em 31/03/2026 em 23 dias. Amil anunciou reajuste médio de 11,3% para PMEs SP. Bradesco e SulAmérica têm janela de desconto de 8% para novos clientes.",
    suggestedAction:
      "Acionar a janela consultiva com benchmark atualizado. Recomendar migração para Bradesco Nacional III (5 vidas+) com carência reduzida.",
    potentialRevenue: 620,
    status: "em_atuacao",
    owner: "Lucas Azevedo",
  },
  {
    id: "trig-002",
    policyId: "pol-008",
    clientId: "cli-005",
    type: "sinistralidade_alta",
    severity: "high",
    detectedAt: "2026-04-22T11:00:00Z",
    title: "Sinistralidade acima da média — Padaria Pão Quente",
    rationale:
      "Três sinistros nos últimos 8 meses. Risk score reduzido. MAG provavelmente aplicará sub-ajuste de 18% na renovação. Icatu aceita carteira com scoring melhor via migração.",
    suggestedAction:
      "Propor migração para Icatu Empresa Plus com preservação de benefícios e ganho de 12% em comissionamento.",
    potentialRevenue: 280,
    status: "aberto",
    owner: "Juliana Paes",
  },
  {
    id: "trig-003",
    policyId: "pol-002",
    clientId: "cli-001",
    type: "mudanca_comissao",
    severity: "medium",
    detectedAt: "2026-04-15T09:30:00Z",
    title: "Nova tabela Icatu — aumento de 6% na comissão",
    rationale:
      "Icatu revisou tabela de comissionamento em abril/26, elevando comissão para apólices de 5–20 vidas de 38% para 44%.",
    suggestedAction:
      "Renegociar renovação mantendo valor ao cliente — gain interno de comissão sem repassar aumento.",
    potentialRevenue: 49,
    status: "aberto",
    owner: "Lucas Azevedo",
  },
  {
    id: "trig-004",
    policyId: "pol-012",
    clientId: "cli-008",
    type: "aniversario_30d",
    severity: "high",
    detectedAt: "2026-04-02T08:00:00Z",
    title: "Renovação em 30 dias — Farma Saúde Unimed",
    rationale:
      "Apólice vence em 28/02 — 35 dias. Histórico de 0 sinistros graves. Unimed aplicará reajuste médio de 13%. Bradesco e SulAmérica apresentaram cotações 9% inferiores.",
    suggestedAction:
      "Preparar comparativo com 3 operadoras e agendar reunião de renovação com a HR.",
    potentialRevenue: 1540,
    status: "em_atuacao",
    owner: "Lucas Azevedo",
  },
  {
    id: "trig-005",
    policyId: "pol-006",
    clientId: "cli-004",
    type: "mudanca_porte",
    severity: "medium",
    detectedAt: "2026-04-10T14:20:00Z",
    title: "Martins Advocacia cruzou limite de porte EPP",
    rationale:
      "Faturamento 2025 ultrapassou R$4,8 mi (limite EPP). Passa a ser Média empresa em 2026, habilitando tarifas diferenciadas e produto RC ampliado.",
    suggestedAction:
      "Oferecer upgrade do RC Profissional com limites maiores + D&O executivo para os 3 sócios.",
    potentialRevenue: 1120,
    status: "aberto",
    owner: "Ana Ribeiro",
  },
  {
    id: "trig-006",
    policyId: "pol-003",
    clientId: "cli-002",
    type: "concorrente_mais_barato",
    severity: "info",
    detectedAt: "2026-04-20T16:45:00Z",
    title: "Bradesco lançou Vida Grupo Digital — 8% mais barato",
    rationale:
      "Novo produto Bradesco Vida Grupo Digital tem prêmio 8% inferior para perfil similar, com cobertura equivalente. Cliente ainda em vigência — oportunidade de pró-atividade.",
    suggestedAction:
      "Informar o cliente pró-ativamente na próxima conversa, fortalecer relacionamento e reservar upgrade para renovação.",
    status: "aberto",
    owner: "Lucas Azevedo",
  },
  {
    id: "trig-007",
    policyId: "pol-009",
    clientId: "cli-006",
    type: "reajuste_anunciado",
    severity: "medium",
    detectedAt: "2026-04-21T10:00:00Z",
    title: "Bradesco anunciou reajuste Nacional III — +9,7%",
    rationale:
      "Reajuste anual Bradesco Nacional III divulgado em 21/04 para vigências a partir de set/26. Stella Cosméticos renova em 15/09 — tempo para comparar alternativas.",
    suggestedAction:
      "Iniciar processo consultivo de pré-renovação 120 dias antes com 3 opções comparativas.",
    potentialRevenue: 1740,
    status: "aberto",
    owner: "Lucas Azevedo",
  },
  {
    id: "trig-008",
    policyId: "pol-011",
    clientId: "cli-007",
    type: "aniversario_60d",
    severity: "high",
    detectedAt: "2026-04-10T09:00:00Z",
    title: "Bellaverde inadimplente há 45 dias",
    rationale:
      "Dois boletos em atraso. Apólice suspensa em 10/04. Risco de cancelamento definitivo em 30 dias.",
    suggestedAction:
      "Ativar protocolo de retenção: renegociação, prorrogação e opção parcelada.",
    status: "em_atuacao",
    owner: "Juliana Paes",
  },
];

// ============================================================================
// CAMPANHAS DE MÍDIA
// ============================================================================
export const campaigns: Campaign[] = [
  {
    id: "camp-001",
    name: "Vida Empresarial — SP Broad",
    channel: "google",
    product: "vida-empresarial",
    status: "ativa",
    startedAt: "2026-03-10",
    budget: 18000,
    spent: 12400,
    leads: 284,
    mql: 96,
    sql: 38,
    won: 12,
    cac: 1033,
    cpl: 43.66,
  },
  {
    id: "camp-002",
    name: "Vida Tech — Lookalike",
    channel: "meta",
    product: "vida-empresarial",
    status: "ativa",
    startedAt: "2026-03-22",
    budget: 12000,
    spent: 8200,
    leads: 411,
    mql: 112,
    sql: 32,
    won: 8,
    cac: 1025,
    cpl: 19.95,
  },
  {
    id: "camp-003",
    name: "Saúde Coletiva — SP Exact",
    channel: "google",
    product: "saude-coletiva",
    status: "ativa",
    startedAt: "2026-02-01",
    budget: 32000,
    spent: 29100,
    leads: 156,
    mql: 74,
    sql: 28,
    won: 9,
    cac: 3233,
    cpl: 186.54,
  },
  {
    id: "camp-004",
    name: "Frota — Decisores LinkedIn",
    channel: "linkedin",
    product: "frota-leve",
    status: "ativa",
    startedAt: "2026-04-01",
    budget: 14000,
    spent: 5800,
    leads: 44,
    mql: 18,
    sql: 7,
    won: 2,
    cac: 2900,
    cpl: 131.82,
  },
  {
    id: "camp-005",
    name: "Odonto Self-Service — WhatsApp",
    channel: "whatsapp",
    product: "odonto-col",
    status: "ativa",
    startedAt: "2026-04-05",
    budget: 3000,
    spent: 1150,
    leads: 221,
    mql: 148,
    sql: 76,
    won: 28,
    cac: 41,
    cpl: 5.2,
  },
  {
    id: "camp-006",
    name: "Nurturing Carteira — Renovação",
    channel: "email",
    product: "multi",
    status: "ativa",
    startedAt: "2026-01-15",
    budget: 0,
    spent: 0,
    leads: 48,
    mql: 48,
    sql: 31,
    won: 19,
    cac: 0,
    cpl: 0,
  },
];

// ============================================================================
// PARCEIROS
// ============================================================================
export const partners: Partner[] = [
  {
    id: "par-001",
    name: "AuditCont Contabilidade",
    tipo: "contador",
    uf: "SP",
    indications: 32,
    converted: 14,
    commissionShare: 0.2,
    earnedYtd: 28400,
    status: "ativo",
  },
  {
    id: "par-002",
    name: "Sindilojas Porto Alegre",
    tipo: "sindicato",
    uf: "RS",
    indications: 86,
    converted: 22,
    commissionShare: 0.1,
    earnedYtd: 18900,
    status: "ativo",
  },
  {
    id: "par-003",
    name: "OAB-SP 44ª Subseção",
    tipo: "associacao",
    uf: "SP",
    indications: 41,
    converted: 19,
    commissionShare: 0.15,
    earnedYtd: 34100,
    status: "ativo",
  },
  {
    id: "par-004",
    name: "Joana Prado — RH Consulting",
    tipo: "influenciador",
    uf: "SP",
    indications: 18,
    converted: 9,
    commissionShare: 0.25,
    earnedYtd: 12800,
    status: "ativo",
  },
  {
    id: "par-005",
    name: "Rede Afiliados Seguros.PRO",
    tipo: "afiliado",
    uf: "BR",
    indications: 212,
    converted: 41,
    commissionShare: 0.1,
    earnedYtd: 46200,
    status: "ativo",
  },
  {
    id: "par-006",
    name: "Escritório Contábil Minerva",
    tipo: "contador",
    uf: "MG",
    indications: 11,
    converted: 3,
    commissionShare: 0.2,
    earnedYtd: 4200,
    status: "onboarding",
  },
];

// ============================================================================
// ATIVIDADES (timeline)
// ============================================================================
export const activities: Activity[] = [
  {
    id: "act-001",
    leadId: "lead-002",
    type: "quote_sent",
    title: "Proposta enviada — 2 opções Amil/Bradesco",
    by: "Lucas Azevedo",
    at: "2026-04-21T16:30:00Z",
  },
  {
    id: "act-002",
    leadId: "lead-002",
    type: "proposal_viewed",
    title: "Proposta aberta 3x pela Beatriz",
    by: "Sistema",
    at: "2026-04-22T11:08:00Z",
  },
  {
    id: "act-003",
    leadId: "lead-002",
    type: "whatsapp",
    title: "WhatsApp: tirando dúvida sobre coparticipação",
    by: "Beatriz Gomes",
    at: "2026-04-22T14:20:00Z",
  },
  {
    id: "act-004",
    leadId: "lead-001",
    type: "call",
    title: "Call discovery 32min — mapeada necessidade de capital elevado p/ sócios",
    by: "Ana Ribeiro",
    at: "2026-04-20T10:00:00Z",
  },
  {
    id: "act-005",
    clientId: "cli-001",
    type: "note",
    title: "Gatilho de renovação ativado pelo motor",
    description:
      "Motor de re-oferta detectou janela de 60d para renovação da apólice Amil. Lucas acionou fluxo consultivo.",
    by: "Motor Affida",
    at: "2026-04-18T08:00:00Z",
  },
];

// ============================================================================
// COTAÇÃO EXEMPLO — Adiantajus (replica a proposta real)
// ============================================================================
export const sampleQuote: Quote = {
  id: "quote-adiantajus-001",
  clientId: "cli-001",
  product: "saude-coletiva",
  createdAt: "2026-03-20T10:00:00Z",
  expiresAt: "2026-03-30T23:59:00Z",
  vidas: 7,
  faixas: [
    { label: "19 a 23 anos", count: 1 },
    { label: "29 a 33 anos", count: 6 },
  ],
  packages: [
    {
      id: "pkg-amil-op1",
      operatorId: "amil",
      plano: "S380 / S750 R1 / S2500 R1",
      acomodacao: "Apartamento",
      coparticipacao: "parcial",
      abrangencia: "Nacional",
      reembolsoConsulta: 432,
      valorMensalPorVida: 1083.71,
      valorMensalTotal: 7586,
      carencia: {
        Consulta: "0 dias",
        "Exames especiais": "0 dias",
        Internações: "0 dias",
        Terapias: "180 dias",
        Obstetrícia: "300 dias",
      },
      redeDestaque: ["H. Samaritano", "H. Oswaldo Cruz", "H. Sírio Libanês (S2500)", "H. Albert Einstein (S2500)"],
      promocoes: ["Amil Dental básico — gratuito 12 meses"],
    },
    {
      id: "pkg-bradesco-op1",
      operatorId: "bradesco-saude",
      plano: "Efetivo / Nacional III / Nacional Plus",
      acomodacao: "Apartamento",
      coparticipacao: "sem",
      abrangencia: "Nacional",
      reembolsoConsulta: 439,
      valorMensalPorVida: 1300.27,
      valorMensalTotal: 9101.9,
      carencia: {
        Consulta: "0 dias",
        "Exames especiais": "0 dias",
        Internações: "0 dias",
        Terapias: "180 dias",
        Obstetrícia: "300 dias",
      },
      redeDestaque: ["H. BP", "H. Oswaldo Cruz", "H. Sírio Libanês (Plus)", "H. Albert Einstein (Plus)"],
    },
  ],
  status: "enviada",
};

// ============================================================================
// SUMÁRIOS / MÉTRICAS (pré-calculados pra dashboards)
// ============================================================================
export const kpis = {
  mrr: clients.reduce((acc, c) => acc + c.monthlyRevenue, 0),
  activeClients: clients.filter((c) => c.status === "ativo").length,
  activeLives: clients.reduce((acc, c) => acc + c.vidas, 0),
  openTriggers: reofferTriggers.filter((t) => t.status === "aberto").length,
  inPipeline: leads.filter((l) => !["fechado", "perdido"].includes(l.stage)).length,
  pipelineValue: leads
    .filter((l) => !["fechado", "perdido"].includes(l.stage))
    .reduce((acc, l) => acc + l.estimatedCommission, 0),
  activeCampaigns: campaigns.filter((c) => c.status === "ativa").length,
  totalCampaignSpent: campaigns.reduce((acc, c) => acc + c.spent, 0),
  totalCampaignLeads: campaigns.reduce((acc, c) => acc + c.leads, 0),
};

// Stages do pipeline — paleta estrita Manual de Marca Affida (dez/2025):
// Navy (Dress Blues + Midnight) · Champagne (UP + Greige) · Forest (Brown) · Ivory + Ink.
export const pipelineStages = [
  { id: "novo", label: "Novo", color: "bg-navy-100 text-navy-800" },
  { id: "qualificado", label: "Qualificado", color: "bg-champagne-50 text-navy-700" },
  { id: "proposta", label: "Proposta enviada", color: "bg-champagne-100 text-champagne-800" },
  { id: "negociacao", label: "Negociação", color: "bg-champagne-200 text-champagne-900" },
  { id: "fechado", label: "Fechado", color: "bg-forest-50 text-forest-700" },
  { id: "perdido", label: "Perdido", color: "bg-navy-200 text-navy-900" },
] as const;

export const team = [
  { id: "ana", name: "Ana Ribeiro", role: "Closer Sênior", avatar: "AR", initials: "AR" },
  { id: "lucas", name: "Lucas Azevedo", role: "Closer Sênior", avatar: "LA", initials: "LA" },
  { id: "juliana", name: "Juliana Paes", role: "SDR Especialista", avatar: "JP", initials: "JP" },
  { id: "carlos", name: "Carlos Nardone", role: "CEO", avatar: "CN", initials: "CN" },
];
